spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/saga_db
spring.datasource.username=saga_user
spring.datasource.password=saga_pass
spring.jpa.hibernate.ddl-auto=update